# Generated by Django 2.2.3 on 2019-07-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('sn_pow', models.CharField(max_length=255)),
                ('sn_gas', models.CharField(max_length=255)),
                ('cons_1', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cons_2', models.DecimalField(decimal_places=3, max_digits=9)),
                ('prod_1', models.DecimalField(decimal_places=3, max_digits=9)),
                ('prod_2', models.DecimalField(decimal_places=3, max_digits=9)),
                ('gas', models.DecimalField(decimal_places=3, max_digits=9)),
                ('pow_fail', models.IntegerField(default=-1)),
                ('long_pow_fail', models.IntegerField(default=-1)),
                ('vol_sag_1', models.IntegerField(default=-1)),
                ('vol_sag_2', models.IntegerField(default=-1)),
                ('vol_sag_3', models.IntegerField(default=-1)),
                ('vol_swell_1', models.IntegerField(default=-1)),
                ('vol_swell_2', models.IntegerField(default=-1)),
                ('vol_swell_3', models.IntegerField(default=-1)),
                ('last_raw', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(editable=False)),
                ('tariff', models.SmallIntegerField(editable=False)),
                ('consumption', models.DecimalField(decimal_places=3, editable=False, max_digits=9)),
                ('production', models.DecimalField(decimal_places=3, editable=False, max_digits=9)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_measurements', to='smart_energy.Meter')),
            ],
        ),
        migrations.CreateModel(
            name='GasMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(editable=False)),
                ('consumption', models.DecimalField(decimal_places=3, editable=False, max_digits=9)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_measurements', to='smart_energy.Meter')),
            ],
        ),
    ]
