# Generated by Django 2.2.3 on 2019-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_energy', '0002_meter_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasmeasurement',
            name='hour_avg',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='gasmeasurement',
            name='min_avg',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='powermeasurement',
            name='hour_avg',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='powermeasurement',
            name='min_avg',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=9, null=True),
        ),
    ]
