# Generated by Django 2.2.3 on 2019-07-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_energy', '0003_auto_20190730_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasmeasurement',
            old_name='hour_avg',
            new_name='avg_hour_consumption',
        ),
        migrations.RenameField(
            model_name='gasmeasurement',
            old_name='min_avg',
            new_name='avg_min_consumption',
        ),
        migrations.RenameField(
            model_name='powermeasurement',
            old_name='hour_avg',
            new_name='avg_hour_consumption',
        ),
        migrations.RenameField(
            model_name='powermeasurement',
            old_name='min_avg',
            new_name='avg_hour_production',
        ),
        migrations.AddField(
            model_name='powermeasurement',
            name='avg_min_consumption',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='powermeasurement',
            name='avg_min_production',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=9, null=True),
        ),
    ]
